#!/bin/bash

langs=("deu" "eng")

for file in *.mkv; do
	#aquiring tracks to extract
	for lang in $langs; do
		tracks=()
		tracks+=$(ffprobe "$file" -v quiet -print_format json -show_format -show_streams | jq '.streams[] | select(.codec_name=="hdmv_pgs_subtitle") | select(.tags.language=="'$lang'") | .index')
		idx=1
		for track in $tracks; do
			echo ${file%.*} - ${lang}:
			$(ffmpeg -v quiet -stats -i "$file" -map 0:$track -c:s copy "${file%.*}-${lang}-${idx}.sup")
			idx+=1
		done
	done
done
